Backports it to guillotina 3.2.18
onna/guillotina_amqp pull request #1
Opened 2018-12-19 17:16 UTC by lferran

2018-12-19 17:29 UTC, lferran commented
@vangheem I'm getting 401 on the `test_api.py`. Seems like root does not have access to the package endpoints.

It's weird. Any idea why? Is `guillotina.Manage` not given to `root` by default?

2018-12-19 17:34 UTC, vangheem requested changes

2018-12-19 17:34 UTC, vangheem commented on setup.py
> +            'pytest-docker-fixtures[rabbitmq]==1.2.7',
It's not a good idea to use hard-pins in setup.py--you're forcing consumers to use this.

Can you change it to `>=`?

2018-12-19 17:35 UTC, vangheem approved these changes

2018-12-19 17:35 UTC, vangheem commented on setup.py
> +        'guillotina==3.2.18',
Do not use fixed version here. `>=`.

2018-12-19 17:35 UTC, vangheem commented on setup.py
> +        'guillotina_rediscache<=2.0.4',
Why this?

2018-12-19 17:35 UTC, vangheem commented on setup.py
> +        'guillotina_rediscache<=2.0.4',
Just remove the version constraint if it works forward and backward.

2018-12-19 17:36 UTC, vangheem requested changes
please fix version pinning issues.

2018-12-19 17:37 UTC, vangheem commented
oh, I just noticed this isn't guillotinaweb. You forked it? I guess you can do whatever you want if you forked it then :)

As far as I can see, `guillotina.Manage` isn't actually a permission defined anywhere.

2018-12-19 17:40 UTC, lferran commented
yes I forked it just so guillotina 3.2.18 can use it :+1: 
Thanks for the quick feedback !!

2018-12-19 18:03 UTC, lferran commented
ouch.. the tests are passing green but actually they are failing:
```
INFO:guillotina_amqp.worker:Finished task: 80284853-9344-4d1c-adce-64d935249d7b: guillotina_amqp.utils._run_object_task
PASSEDDEBUG:guillotina_amqp:autokill: No beacons received
ERROR:guillotina_amqp:Exiting worker because of no beacon activity
The command "pytest -s --cov=guillotina_amqp -s --tb=native -v --cov-report term-missing --cov-append guillotina_amqp" exited with 0.
```

This might aswell be happening in the upstream branch

2018-12-19 18:04 UTC, vangheem commented
See https://github.com/guillotinaweb/guillotina_amqp/commit/497bbc6ae97b1143dfa28c1027ca93490f5f886e ?

2018-12-19 18:17 UTC, lferran commented
mmm it must be something else, since this commit is also included in this fork.
I'll look tomorrow

2018-12-20 08:29 UTC, lferran commented
> `guillotina.AccessContent` is really open permission. I suggest creating your own permission and granting `guillotina.Manager` role.

@vangheem I'll fix this on the upstream branch aswell, ok? 
https://github.com/guillotinaweb/guillotina_amqp/pull/12

2018-12-20 09:31 UTC, lferran commented
> ouch.. the tests are passing green but actually they are failing:
> 
> ```
> INFO:guillotina_amqp.worker:Finished task: 80284853-9344-4d1c-adce-64d935249d7b: guillotina_amqp.utils._run_object_task
> PASSEDDEBUG:guillotina_amqp:autokill: No beacons received
> ERROR:guillotina_amqp:Exiting worker because of no beacon activity
> The command "pytest -s --cov=guillotina_amqp -s --tb=native -v --cov-report term-missing --cov-append guillotina_amqp" exited with 0.
> ```
> This might aswell be happening in the upstream branch

yup, the same is happening in the main repo: https://travis-ci.org/guillotinaweb/guillotina_amqp/builds/470408125?utm_source=github_status&utm_medium=notification

2018-12-20 09:32 UTC, merged